name: nyt_flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  stacked_generator: ^1.6.1


flutter:

  uses-material-design: true

  assets:
    - .env